name: Build image and push on Docker Hub

on: 
  push: 
    branches: [main]

  workflow_dispatch:
    
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
   
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21
          
