name: Build image and push on Docker Hub

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Testing
      - run: echo Hello!
    
