name: Build image and push on Docker Hub

on: 
  push: 
    branches: [main]

  workflow_dispatch:
    
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
   
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21

      - name: Get current package version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Login on Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image using Dockerfile and push on Docker Hub
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            rodazuos/annotation-api:latest
            rodazuos/annotation-api:${{ steps.package-version.outputs.current-version }}
